#!/bin/bash
vpspackversion=5.1
OS=`uname -m`;
host=`hostname`;
ip=`cat /etc/VpsPackdir/ip`;
function stunnelnm(){
echo "Instalando Stunnel, Espere..."
bash /etc/VpsPackdir/ssl
}
function stunnelmulti(){
echo "Instalando Stunnel, Espere..."
bash /etc/VpsPackdir/sslmulti
}
if [[ $1 == "" ]]
then
clear
figlet -p -f smslant < /root/name
echo -e "\033[1;37m 【     ☬ VPSPack v. $vpspackversion ☬     】\033[0m"
echo -e "\033[1;37m › Linux Dist: $distribution › Version: $os_version\033[0m"
echo -e "\033[1;37m › IP Publica VPS:\033[1;32m$ip \033[0m"
echo -e "\033[1;37m › Hostname VPS:\033[1;32m$host \033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ────────────────── /// ────────────────\033[1;33m"
echo -e "\033[1;37m     STUNNEL SSL\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;31m ────────────────── /// ────────────────\033[1;33m"
echo -e "[\033[1;32m1\033[1;33m]   \033[1;31m› \033[1;33mSTUNNEL NORMAL\033[1;33m
[\033[1;32m2\033[1;33m]   \033[1;31m› \033[1;33mSTUNNEL MULTI CERTIFICADO\033[1;33m
[\033[1;30m0\033[1;33m] < REGRESAR \033[1;33m
[\033[1;31m-\033[1;33m]\033[1;31m ───────────────── /// ─────────────────\033[1;33m"
echo -e "\033[1;33m      ⋤⋥ ESCRIBA UNA OPCION:      \033[0m"
read -p "⛛ : " opcao
tput cuu1 >&2 && tput dl1 >&2
else
opcao=$1
fi
case $opcao in
1 | 01 )
stunnelnm;;
2 | 02 )
stunnelmulti;;
0)
vpspack 10;;
esac