#!/bin/bash
read -p "Nombre del usuario a modificar: " namer
 if cat /etc/passwd |grep $namer: > /dev/null
 then
 echo " "
 else
 echo "Usuario $namer no existe"
 vpspack 2
 exit
 fi
echo -e "\033[1;33mCuantos dias deseas renovar el usuario ?\033[1;33m"
read -p ">: " option
chage -E `date -d "$option days" +"%Y-%m-%d"` $namer
echo -e "Se agregaron $option dias al usuario $namer"
echo -e "\033[1;31mPRESIONE ENTER PARA CONTINUAR\033[0m"
read -p " "
vpspack 2
