#!/bin/bash
vpspackversion=5.8
OS=`uname -m`;
fecha=`date`;
IP=$(wget -qO- ipv4.icanhazip.com)
fun_bar () {
comando[0]="$1"
comando[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
) > /dev/null 2>&1 &
tput civis
echo -ne "  \033[1;33mESPERE \033[1;37m- \033[1;33m["
while true; do
for((i=0; i<18; i++)); do
echo -ne "\033[1;31mΔ"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[1;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[1;33mESPERE\033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
if [ $(id -u) != 0 ]
then
echo "Ejecute el script como root"
exit
fi
clear
cd /root
mkdir /etc/VpsPackdir  2>/dev/null
apt-get install curl -y 1> /dev/null 2> /dev/null
apt-get install zip -y 1> /dev/null 2> /dev/null
curl -o /etc/VpsPackdir/logo http://vpspack.powsitos.com:5000/58BMPSCAXK/logo 1> /dev/null 2> /dev/null
cat /etc/VpsPackdir/logo
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m ───────────────────────────────────────\033[1;33m"
echo -e "\033[1;33mInstalando \033[1;32mVPSPack $vpspackversion\033[0m"
echo -e "\033[1;33mEspere por favor\033[0m"
echo -e "\033[1;33mSe instalaran los paquetes necesarios\033[0m"
echo -e "\033[1;33mGrupo de Telegram: @PwrMX & @VPNMX\033[0m"
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m ───────────────────────────────────────\033[1;33m"
sleep 5
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Preparando Sistema\033[1;33m"
function preparar(){
touch /root/usuarios.db
touch /root/badvpn.log
mkdir /etc/VpsPackdir/limite 2>/dev/null
mkdir /etc/VpsPackdir/senha 2>/dev/null
mkdir /etc/VpsPackdir/v 2>/dev/null
mkdir /etc/VpsPackdir/socks 2>/dev/null
rm -rf /etc/VpsPackdir/fecha 2>/dev/null
rm -rf /root/name 2>/dev/null
rm -rf /bin/limite 2>/dev/null
curl -o /bin/limite http://vpspack.powsitos.com:5000/58BMPSCAXK/limite 1> /dev/null 2> /dev/null
chmod +x /bin/limite
rm -rf /etc/VpsPackdir/sshconf 2>/dev/null
curl -o /etc/VpsPackdir/sshconf http://vpspack.powsitos.com:5000/58BMPSCAXK/sshconf 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/bbrplus.sh 2>/dev/null
curl -o /etc/VpsPackdir/bbrplus.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/bbrplus.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/bbrplus.sh
rm -rf /etc/VpsPackdir/sslhconf 2>/dev/null
curl -o /etc/VpsPackdir/sslhconf http://vpspack.powsitos.com:5000/58BMPSCAXK/sslhconf 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/sslhconf
rm -rf /bin/criarusuario
curl -o /bin/criarusuario http://vpspack.powsitos.com:5000/58BMPSCAXK/criarusuario 1> /dev/null 2> /dev/null
chmod +x /bin/criarusuario
rm -rf /bin/deletarusuario
curl -o /bin/deletarusuario http://vpspack.powsitos.com:5000/58BMPSCAXK/deletarusuario 1> /dev/null 2> /dev/null
chmod +x /bin/deletarusuario
rm -rf /bin/redefinirusuario
curl -o /bin/redefinirusuario http://vpspack.powsitos.com:5000/58BMPSCAXK/redefinirusuario 1> /dev/null 2> /dev/null
chmod +x /bin/redefinirusuario
rm -rf /bin/renovarusuario
curl -o /bin/renovarusuario http://vpspack.powsitos.com:5000/58BMPSCAXK/renovarusuario 1> /dev/null 2> /dev/null
chmod +x /bin/renovarusuario
rm -rf /bin/vpspack
curl -o /bin/vpspack http://vpspack.powsitos.com:5000/58BMPSCAXK/vpspack 1> /dev/null 2> /dev/null
chmod +x /bin/vpspack
rm -rf /bin/speedtest.py
curl -o /bin/speedtest.py http://vpspack.powsitos.com:5000/58BMPSCAXK/speedtest.py 1> /dev/null 2> /dev/null
chmod +x /bin/speedtest.py
rm -rf /bin/toolmaster
curl -o /bin/toolmaster http://vpspack.powsitos.com:5000/58BMPSCAXK/toolmaster 1> /dev/null 2> /dev/null
chmod +x /bin/toolmaster
rm -rf /etc/VpsPackdir/pl.sh
curl -o /etc/VpsPackdir/pl.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/pl.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/pl.sh
rm -rf /etc/VpsPackdir/d.sh
curl -o /etc/VpsPackdir/d.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/d.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/d.sh
rm -rf /root/dropbear
curl -o /root/dropbear http://vpspack.powsitos.com:5000/58BMPSCAXK/dropbear 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/ssl
curl -o /etc/VpsPackdir/ssl http://vpspack.powsitos.com:5000/58BMPSCAXK/ssl 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/sslmulti
curl -o /etc/VpsPackdir/sslmulti http://vpspack.powsitos.com:5000/58BMPSCAXK/sslmulti 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/stunnel
curl -o /etc/VpsPackdir/stunnel http://vpspack.powsitos.com:5000/58BMPSCAXK/stunnel 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/shadowsocks.sh
curl -o /etc/VpsPackdir/shadowsocks.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/shadowsocks.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/shadowsocks.sh
rm -rf /bin/instaladores
curl -o /bin/instaladores http://vpspack.powsitos.com:5000/58BMPSCAXK/instaladores 1> /dev/null 2> /dev/null
chmod +x /bin/instaladores
rm -rf /etc/VpsPackdir/proxyredir.py
curl -o /etc/VpsPackdir/proxyredir.py http://vpspack.powsitos.com:5000/58BMPSCAXK/proxy.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/proxysocket.py
curl -o /etc/VpsPackdir/proxysocket.py http://vpspack.powsitos.com:5000/58BMPSCAXK/proxysocket.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/openvpn-install.sh
curl -o /etc/VpsPackdir/openvpn-install.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/openvpn-install.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/openvpn-install.sh
rm -rf /etc/VpsPackdir/openvpn-auth.sh
curl -o /etc/VpsPackdir/openvpn-auth.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/openvpn-auth.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/openvpn-auth.sh
rm -rf /etc/VpsPackdir/confdropbear
curl -o /etc/VpsPackdir/confdropbear http://vpspack.powsitos.com:5000/58BMPSCAXK/confdropbear 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/dropxbear
curl -o /etc/VpsPackdir/dropxbear http://vpspack.powsitos.com:5000/58BMPSCAXK/dropxbear 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/dropxbear
rm -rf /etc/VpsPackdir/droplimit.sh
curl -o /etc/VpsPackdir/droplimit.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/droplimit.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/droplimit.sh
rm -rf /etc/VpsPackdir/badvpncron.sh
curl -o /etc/VpsPackdir/badvpncron.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/badvpncron.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/badvpncron.sh
rm -rf /etc/VpsPackdir/danted.sh
curl -o /etc/VpsPackdir/danted.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/danted.sh 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/limpieza.sh
curl -o /etc/VpsPackdir/limpieza.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/limpieza.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/limpieza.sh
rm -rf /etc/VpsPackdir/enlinea.sh
curl -o /etc/VpsPackdir/enlinea.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/enlinea.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/enlinea.sh
rm -rf /etc/VpsPackdir/badudp.sh
curl -o /etc/VpsPackdir/badudp.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/badudp.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/badudp.sh
rm -rf /etc/VpsPackdir/badvpncheck.sh
curl -o /etc/VpsPackdir/badvpncheck.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/badvpncheck.sh 1> /dev/null 2> /dev/null
chmod +x /etc/VpsPackdir/badudp.sh
rm -rf /etc/VpsPackdir/PGet.py
curl -o /etc/VpsPackdir/PGet.py http://vpspack.powsitos.com:5000/58BMPSCAXK/PGet.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/Directo.py
curl -o /etc/VpsPackdir/Directo.py http://vpspack.powsitos.com:5000/58BMPSCAXK/Directo.py 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/priv.sh
curl -o /etc/VpsPackdir/priv.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/priv.sh 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/pub.sh
curl -o /etc/VpsPackdir/pub.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/pub.sh 1> /dev/null 2> /dev/null
rm -rf /etc/VpsPackdir/badcron.sh
curl -o /etc/VpsPackdir/badcron.sh http://vpspack.powsitos.com:5000/58BMPSCAXK/badcron.sh 1> /dev/null 2> /dev/null
rm /etc/VpsPackdir/socks/s.zip
curl -o /etc/VpsPackdir/socks/s.zip http://vpspack.powsitos.com:5000/58BMPSCAXK/s.zip
cd /etc/VpsPackdir/socks/
unzip s.zip
rm /etc/VpsPackdir/socks/s.zip
cd /root
if grep vpspack /etc/ssh/sshd_config; then
echo "vpspack found OK"
else
cp /etc/VpsPackdir/sshconf /etc/ssh/sshd_config;
service ssh restart
echo "Configurado"
fi
if [ -f /etc/banner ];
then
echo "Banner Detectado"
else
curl -o /etc/banner http://vpspack.powsitos.com:5000/58BMPSCAXK/banner 1> /dev/null 2> /dev/null
fi
chmod +x /root/dropbear
}
fun_bar 'preparar'
function paquetes(){
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Instalando Paquetes\033[1;33m"
sed -i '/neofetch/d' /etc/apt/sources.list
apt-get update
apt-get -y install nano 1> /dev/null 2> /dev/null
apt-get -y install net-tools 1> /dev/null 2> /dev/null
apt-get -y install iptables 1> /dev/null 2> /dev/null
apt-get -y install unzip 1> /dev/null 2> /dev/null
apt-get -y install htop 1> /dev/null 2> /dev/null
apt-get -y install curl 1> /dev/null 2> /dev/null
apt-get -y install figlet 1> /dev/null 2> /dev/null
apt-get -y install locate 1> /dev/null 2> /dev/null
apt-get -y install zip 1> /dev/null 2> /dev/null
apt-get -y install git 1> /dev/null 2> /dev/null
apt-get -y install build-essential libpq-dev libffi-dev zlib1g-dev 1> /dev/null 2> /dev/null
apt-get -y install screen 1> /dev/null 2> /dev/null
apt-get -y install python-pip 1> /dev/null 2> /dev/null
apt-get -y install python3-pip 1> /dev/null 2> /dev/null
apt-get -y install nload 1> /dev/null 2> /dev/null
apt-get -y install dos2unix 1> /dev/null 2> /dev/null
apt-get -y install lsof 1> /dev/null 2> /dev/null
apt-get -y install speedtest-cli 1> /dev/null 2> /dev/null
apt-get -y install openssl libssl-dev pkg-config 1> /dev/null 2> /dev/null
pip install speedtest-cli > /dev/null 2>&1
apt-get remove apache2 -y && apt-get purge apache2 -y 1> /dev/null 2> /dev/null
rm -rf /var/wwww/html/* 1> /dev/null 2> /dev/null
service apache2 stop 1> /dev/null 2> /dev/null
apt-get install apache2 -y 1> /dev/null 2> /dev/null
sed -i 's/Listen 80/Listen 85/g' /etc/apache2/ports.conf 1> /dev/null 2> /dev/null
rm /var/www/html/index.html 1> /dev/null 2> /dev/null
wget -o /dev/null -O- wget https://raw.githubusercontent.com/kirrathmx/dl/master/index.txt > /var/www/html/index.html
cd /root
service apache2 restart 1> /dev/null 2> /dev/null
mkdir /var/www/html/openvpn
apt-get install -y neofetch 1> /dev/null 2> /dev/null
echo -e "[\033[1;31m-\033[1;33m]\033[1;30m Instalacion Finalizada\033[1;33m"
}
fun_bar 'paquetes'
sleep 5
clear
if cat /root/.bashrc | grep vpspack; then
echo -e ":)"
else
echo "clear" >> .bashrc
echo 'cat /etc/VpsPackdir/logo' >> .bashrc
echo 'DATE=$(date +"%d-%m-%y")' >> .bashrc
echo 'TIME=$(date +"%T")' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "Nombre del Servidor : $HOSTNAME"' >> .bashrc
echo 'echo -e "Fecha del Servidor : $DATE"' >> .bashrc
echo 'echo -e "Hora del Servidor : $TIME"' >> .bashrc
echo 'echo -e ""' >> .bashrc
echo 'echo -e "Bienvenido!"' >> .bashrc
echo 'echo -e "Teclee vpspack para ver el listado de comandos."' >> .bashrc
echo 'echo -e ""' >> .bashrc
fi
clear
rm /etc/VpsPackdir/ip
touch /etc/VpsPackdir/ip
echo "$IP" > /etc/VpsPackdir/ip
cat /etc/VpsPackdir/logo
echo -e "\033[1;32mInstalacion Finalizada\n\033[1;30m"
echo -e "\n\033[1;32mvpspack     \033[1;30mMENU DE OPCIONES"
echo -e "\033[1;32mOpcion 1    \033[1;30mINSTALAR SQUID/SSH"
echo -e "\033[1;32mOpcion 2    \033[1;30mADMINISTRACION DE USUARIOS"
echo -e "\033[1;32mOpcion 8    \033[1;30mPUERTOS HABILITADOS"
echo -e "\033[1;32mOpcion 9    \033[1;30mHERRAMIENTAS"
echo -e "\033[1;32mOpcion 10   \033[1;30mINSTALADORES"
echo -e "\033[1;32m@- \033[1;30mGrupo de Telegram : @PwrMX\033[0m"
echo -e "\033[1;32mVersion     \033[1;30m$vpspackversion \033[0m"
echo -e "$fecha" >> /etc/VpsPackdir/fecha
echo -e "\033[1;32m Personalizacion - Escribe tu Nick:\033[0m"
echo -e "\033[1;32m (Maximo 10 Caracteres)\033[0m"
read -p ": " nickname
echo "$nickname" >> /root/name
cd /root
rm signuschris
vpspack